apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: app-conf 
data: 
  profil: kub

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  #namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cobrlt/backend:1.0.0
          ports:
            - containerPort: 8080
              name : backend-port
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/tutorials
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/tutorials
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /api/tutorials
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://database-service:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
          
            # - name: SPRING_PROFILES_ACTIVE
            #   valueFrom:
            #     configMapKeyRef:
            #       name: app-conf
            #       key: profil
            # - name: HOST_NAME_DATABASE
            #   value: "database-service"
            # - name: USERNAME_DB
            #   value: "root"
            # - name: PASSWORD_DB
            #   value: "root"
              # valueFrom:
              #   secretKeyRef:
              #     name: mysql-secret
              #     key: password

