apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: app-conf 
data: 
  profil: docker

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  #namespace: exam
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  #type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  #namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cobrlt/backend:1.0.0
          ports:
            - containerPort: 8080
              name : backend-port
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-conf
                  key: profil
          #-------------------------
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 15
          # startupProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   failureThreshold: 30
          #   periodSeconds: 10

