apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  password: cm9vdAo=  # echo root | base64
---

apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  replicas: 2
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql-container
          image: mysql:latest
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
              # valueFrom:
              #   secretKeyRef:
              #     name: mysql-secret
              #     key: password
            - name: MYSQL_DATABASE
              value: testdb
          volumeMounts:
            - name: mysqlvol-docker
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysqlvol-docker
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
          # -------------------------
          # readinessProbe:
          #   tcpSocket:
          #     port: 3306
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 3306
          #   initialDelaySeconds: 10
          #   periodSeconds: 15
          # startupProbe:
          #   tcpSocket:
          #     port: 3306
          #   failureThreshold: 30
          #   periodSeconds: 10
          # -------------------------

