# Définition d'un PodDisruptionBudget (PDB) pour le frontend dans l'espace de noms "exam"
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb  # Nom du PDB
  namespace: exam    # Espace de noms du PDB
spec:
  minAvailable: 1     # Garantit qu'au moins 1 pod est disponible pendant les perturbations
  selector:
    matchLabels:
      app: frontend   # Sélectionne les pods avec l'étiquette "app: frontend"

---

# Définition d'un PodDisruptionBudget (PDB) pour le backend dans l'espace de noms "exam"
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb   # Nom du PDB
  namespace: exam     # Espace de noms du PDB
spec:
  minAvailable: 1     # Garantit qu'au moins 1 pod est disponible pendant les perturbations
  selector:
    matchLabels:
      app: backend    # Sélectionne les pods avec l'étiquette "app: backend"

---

# Définition d'un PodDisruptionBudget (PDB) pour MySQL dans l'espace de noms "exam"
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-pdb     # Nom du PDB
  namespace: exam     # Espace de noms du PDB
spec:
  minAvailable: 1     # Garantit qu'au moins 1 pod est disponible pendant les perturbations
  selector:
    matchLabels:
      app: mysql      # Sélectionne les pods avec l'étiquette "app: mysql"
