apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: exam
spec:
  minAvailable: 1  # Nombre minimal de pods disponibles pendant une perturbation
  selector:
    matchLabels:
      app: frontend  # Étiquette correspondant à votre application

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: exam
spec:
  minAvailable: 1  # Nombre minimal de pods disponibles pendant une perturbation
  selector:
    matchLabels:
      app: backend

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-pdb
  namespace: exam
spec:
  minAvailable: 1  # Nombre minimal de pods disponibles pendant une perturbation
  selector:
    matchLabels:
      app: mysql