apiVersion: v1
kind: ResourceQuota
metadata:
  name: exam-resource-quota
  namespace: exam
spec:
  hard:
    pods: "20" # Limite le nombre total de Pods dans le namespace
    requests.cpu: "4" # Limite totale de la CPU requise par tous les Pods
    limits.cpu: "6"   # Limite totale de la CPU limitée par tous les Pods
    requests.memory: 4Gi # Limite totale de la mémoire requise par tous les Pods
    limits.memory: 8Gi   # Limite totale de la mémoire limitée par tous les Pods
