apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: exam
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]  # Ajoutez les ressources que vous souhaitez autoriser
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: exam
subjects:
- kind: User
  name: "utilisateur@example.com"  # Remplacez par le nom de l'utilisateur
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
